"""Small demo-store catalog used for aisle routing and price suggestions."""

_ROWS = [
    ("Maruchan Instant Lunch Chicken Flavor", "Instant Meals", 1, 1.49, ["instant noodles", "ramen", "noodles"]),
    ("Maruchan Instant Lunch Beef Flavor", "Instant Meals", 1, 1.49, ["instant noodles", "ramen", "noodles"]),
    ("Maruchan Instant Lunch Cheddar Cheese Flavor", "Instant Meals", 1, 1.49, ["instant noodles", "ramen", "noodles", "cheese"]),
    ("Cup Noodles Chicken Flavor", "Instant Meals", 1, 1.29, ["instant noodles", "ramen", "noodles"]),
    ("Cup Noodles Beef Flavor", "Instant Meals", 1, 1.29, ["instant noodles", "ramen", "noodles"]),
    ("Maruchan Ramen Chicken Flavor 3 oz", "Instant Meals", 1, 0.49, ["ramen", "noodles", "instant noodles"]),
    ("Cheetos Crunchy", "Snacks & Candy", 2, 2.99, ["chips", "cheetos", "crunchy"]),
    ("Cheetos Puffs", "Snacks & Candy", 2, 2.99, ["chips", "cheetos", "puffs"]),
    ("Lay's Classic Potato Chips", "Snacks & Candy", 2, 3.49, ["chips", "potato chips", "crisps"]),
    ("Doritos Nacho Cheese", "Snacks & Candy", 2, 3.49, ["chips", "doritos", "tortilla chips"]),
    ("Takis Fuego", "Snacks & Candy", 2, 3.99, ["chips", "takis", "rolled chips"]),
    ("Haribo Goldbears", "Snacks & Candy", 2, 2.49, ["candy", "gummy candy", "gummy bears"]),
    ("Haribo Twin Snakes", "Snacks & Candy", 2, 2.49, ["candy", "gummy candy", "gummy snakes"]),
    ("Hi-Chew Fruit Chews", "Snacks & Candy", 2, 2.29, ["candy", "chews", "fruit chews"]),
    ("OREO Original Cookies", "Cookies & Crackers", 3, 4.49, ["cookies", "oreo", "sandwich cookies"]),
    ("OREO Double Stuf Cookies", "Cookies & Crackers", 3, 4.99, ["cookies", "oreo", "sandwich cookies"]),
    ("Chips Ahoy! Original Chocolate Chip Cookies", "Cookies & Crackers", 3, 4.49, ["cookies", "chocolate chip cookies", "chocolate chip"]),
    ("Ritz Original Crackers", "Cookies & Crackers", 3, 3.99, ["crackers", "ritz", "round crackers"]),
    ("Goldfish Cheddar Crackers", "Cookies & Crackers", 3, 3.99, ["crackers", "goldfish", "cheese crackers"]),
    ("Core Power Protein Shake", "Refrigerated Foods & Drinks", 4, 4.49, ["protein shake", "milk drink", "bottle"]),
    ("Fairlife Core Power Elite Protein Shake", "Refrigerated Foods & Drinks", 4, 5.49, ["protein shake", "milk drink", "bottle"]),
    ("Chobani Greek Yogurt", "Refrigerated Foods & Drinks", 4, 1.79, ["yogurt", "greek yogurt", "cup"]),
    ("Yoplait Yogurt", "Refrigerated Foods & Drinks", 4, 1.29, ["yogurt", "yogurt cup", "cup"]),
    ("Lunchables Turkey & Cheddar", "Refrigerated Foods & Drinks", 4, 3.49, ["lunch kit", "lunchables", "snack pack"]),
    ("Minute Maid Fruit Punch", "Refrigerated Foods & Drinks", 4, 2.49, ["juice", "fruit punch", "drink"]),
    ("Simply Peach Juice", "Refrigerated Foods & Drinks", 4, 3.49, ["juice", "peach juice", "drink"]),
    ("SunnyD Orange Drink", "Refrigerated Foods & Drinks", 4, 2.49, ["juice", "orange drink", "bottle"]),
    ("Green Giant Mixed Vegetables", "Pantry & Canned Goods", 5, 1.69, ["canned vegetables", "mixed vegetables", "can"]),
    ("Del Monte Diced Tomatoes", "Pantry & Canned Goods", 5, 1.79, ["canned tomatoes", "tomatoes", "can"]),
    ("Del Monte Sweet Peas", "Pantry & Canned Goods", 5, 1.69, ["canned vegetables", "peas", "can"]),
    ("Bush's Best Black Beans", "Pantry & Canned Goods", 5, 1.49, ["canned beans", "black beans", "can"]),
    ("Green Giant Cut Green Beans", "Pantry & Canned Goods", 5, 1.69, ["canned vegetables", "green beans", "can"]),
    ("Poland Spring Water 16.9 fl oz", "Beverages", 6, 1.29, ["water", "bottled water", "water bottle"]),
    ("Aquafina Water 16.9 fl oz", "Beverages", 6, 1.49, ["water", "bottled water", "water bottle"]),
    ("Dasani Water 16.9 fl oz", "Beverages", 6, 1.49, ["water", "bottled water", "water bottle"]),
    ("Califia Farms Almondmilk", "Beverages", 6, 4.49, ["milk", "almond milk", "carton"]),
    ("Simply Lemonade", "Beverages", 6, 3.49, ["lemonade", "juice", "drink"]),
    ("Simply Peach", "Beverages", 6, 3.49, ["juice", "peach juice", "drink"]),
    ("Dawn Ultra Dishwashing Liquid", "Household", 7, 4.99, ["dish soap", "dishwashing liquid", "soap"]),
    ("Palmolive Ultra Dishwashing Liquid", "Household", 7, 3.49, ["dish soap", "dishwashing liquid", "soap"]),
    ("Ajax Dishwashing Liquid", "Household", 7, 2.99, ["dish soap", "dishwashing liquid", "soap"]),
    ("Clorox Disinfecting Wipes", "Household", 7, 5.99, ["disinfecting wipes", "cleaning wipes", "wipes"]),
    ("Glad Food Storage Bags", "Household", 7, 4.49, ["storage bags", "food bags", "bags"]),
    ("Rubber Duck", "Toys & Small Gifts", 8, 3.99, ["rubber duck", "duck", "bath toy"]),
    ("LEGO Creator New York Taxi", "Toys & Small Items", 8, 9.99, ["lego", "building set", "taxi"]),
    ("Reese's Peanut Butter Cups", "Toys & Small Items", 8, 1.49, ["candy", "peanut butter cups", "chocolate"]),
    ("Sour Patch Kids", "Toys & Small Items", 8, 2.49, ["candy", "gummy candy", "gummy pieces"]),
]

CATALOG = [
    {"name": name, "aisle": aisle, "aisle_no": aisle_no, "price": price, "tags": tags}
    for name, aisle, aisle_no, price, tags in _ROWS
]
